name: Elixir CI

on:
  push:

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: isn_test
      POSTGRES_USER: isn
      POSTGRES_PASSWORD: isn_secret_test_password

    steps:
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '14'  # See https://hub.docker.com/_/postgres for available versions
        postgresql db: ${{ env.POSTGRES_DB }}
        postgresql user: ${{ env.POSTGRES_USER }}
        postgresql password: ${{ env.POSTGRES_PASSWORD }}
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.13.4' # Define the elixir version [required]
        otp-version: '24.3.4' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
